### ISSUE TITLE
"Message was successfully sent, but there were no matching targets."

### ISSUE THREAD

**Issue by aliyasar** [BytesGuy/AzureNotificationHub#2]
I have tried Xamarin.Android and Xamarin.Windows push notifications and all works fine. However, on the iOS side, something wrong.

I am trying to add push notifications to my Xamarin.iOS app using these tutorials that one of them is yours.

- https://docs.microsoft.com/en-us/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started

- https://blog.xamarin.com/push-notifications-ios-azure-notification-hubs/ (@BytesGuy)

From Azure Test Send I got **"Message was successfully sent, but there were no matching targets."**

I have followed all the steps as it is but when I put a breakpoint, I always get "IsRegistered = false":

AppDelegate.cs

  ```
private SBNotificationHub Hub { get; set; }
public const string ConnectionString = "Endpoint=sb://...";
public const string NotificationHubPath = "NotificationHubName...";

public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
{
                // Set our preferred notification settings for the app
                var pushSettings = UIUserNotificationSettings.GetSettingsForTypes(
                    UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound,
                    new NSSet());

                // Register for notifications
                UIApplication.SharedApplication.RegisterUserNotificationSettings(pushSettings);
                UIApplication.SharedApplication.RegisterForRemoteNotifications();
                bool IsRegistered = UIApplication.SharedApplication.IsRegisteredForRemoteNotifications;

                return true;
            }

   public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            Hub = new SBNotificationHub(ConnectionString, NotificationHubPath);
            Hub.UnregisterAllAsync(deviceToken, (error) =>
            {
                if (error != null)
                {
                    // Error unregistering
                    return;
                }
                // Register this device with the notification hub
                Hub.RegisterNativeAsync(deviceToken, null, (registerError) =>
                {
                    if (registerError != null)
                    {
                        // Error registering
                    }
                });
            });
        }

        public override void ReceivedRemoteNotification(UIApplication application, NSDictionary userInfo)
        {
            if (null != userInfo && userInfo.ContainsKey(new NSString("aps")))
            {
                // Get the aps dictionary from the alert payload
                NSDictionary aps = userInfo.ObjectForKey(new NSString("aps")) as NSDictionary;
            }
        }
```

My questions are;

1. Why am I not registering?
2. How can I learn why am I not registering?
3. Is Xamarin support iOS 11.0 push notification from Azure Notification Hub?

**Note:** I am using;
- Visual Studio 2017 (Version 15.4.0) on Windows 10
- Mac OS High Siera Version 10.13
- Xcode Version 9.0.1
- VS for Mac Community Version 7.2 (build 636)
- Testing on iPhone 5S, iPhone 6, iPhone 6S, iPhone 7, iPhone 8 - iOS11.0

**Comment by aliyasar** [comment]
Solved it by using physical iPhone device.

> "The simulator does not do Push Notifications. And to push from a server, you have to have device(s) to push to as well as your app on that device."
> "The iPhone Simulator is unable to receive push notifications or successfully register for them."

![image](https://user-images.githubusercontent.com/6706258/32950832-d6733b62-cbb8-11e7-8044-3f1b86ae0d15.png)

**Comment by Srusti-Thakkar** [comment]
Hi. I am doing same thing on for Android And iOS. Currently I am testing on Android and getting same message. How can I solve this?
